name: Testy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Sprawdz repozytoriun
      uses: actions/checkout@v3

    - name: python 3.13.2
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.2'

    - name: Instalowanie zaleznosci
      run: |
        python -m pip install --upgrade pip

    - name: Uruchomienie testow unittest
      run: |
        python -m unittest discover
